/** @jsxImportSource preact */
import type { BlueprintOutput, ClearanceCheck, ComponentListItem, CablePlan } from '../../lib/blueprint';

interface Props {
  blueprint: BlueprintOutput | null;
}

export function BuildBlueprint({ blueprint }: Props) {
  if (!blueprint) {
    return (
      <div class="blueprint-empty-state">
        <h2>Build Blueprint</h2>
        <p>
          Select your components in the Assembly Tray above, then click
          <strong> Generate Blueprint </strong>
          to receive a complete build plan with compatibility checks, build order, tool list, and more.
        </p>
      </div>
    );
  }

  const { summary } = blueprint;

  return (
    <div class="blueprint-container" id="blueprint-output">
      {/* Print header — hidden on screen, shown on print */}
      <div class="blueprint-print-header">
        <h1>PC Build Blueprint</h1>
        <p>
          Generated by PSUCheck.com — {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
        </p>
      </div>

      {/* Summary Stats */}
      <div class="blueprint-summary-grid">
        <div class="blueprint-summary-stat">
          <div class="stat-value">{summary.totalChecks}</div>
          <div class="stat-label">Total Checks</div>
        </div>
        <div class="blueprint-summary-stat">
          <div class="stat-value" style={summary.checksFailed > 0 ? 'color: var(--status-danger);' : 'color: var(--status-safe);'}>
            {summary.checksPassed}
          </div>
          <div class="stat-label">Passed</div>
        </div>
        <div class="blueprint-summary-stat">
          <div class="stat-value" style={summary.checksFailed > 0 ? 'color: var(--status-danger);' : ''}>
            {summary.checksFailed}
          </div>
          <div class="stat-label">Failed</div>
        </div>
        <div class="blueprint-summary-stat">
          <div class="stat-value" style={summary.checksUnknown > 0 ? 'color: var(--status-warning);' : ''}>
            {summary.checksUnknown}
          </div>
          <div class="stat-label">Unknown</div>
        </div>
      </div>

      {/* Component List */}
      <section class="blueprint-section" aria-labelledby="bp-components-heading">
        <h2 id="bp-components-heading">Selected Components</h2>
        <table class="blueprint-table">
          <thead>
            <tr>
              <th scope="col">Category</th>
              <th scope="col">Component</th>
              <th scope="col">Price</th>
              <th scope="col">Status</th>
            </tr>
          </thead>
          <tbody>
            {blueprint.componentList.map(item => (
              <tr key={item.category + item.name}>
                <td style="font-weight:600;color:var(--text-primary);">{item.category}</td>
                <td>{item.name}</td>
                <td style="font-variant-numeric:tabular-nums;">${item.price}</td>
                <td>
                  {item.verified
                    ? <span class="badge badge-safe">Verified</span>
                    : <span class="badge badge-warning">Unconfirmed Specs</span>
                  }
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </section>

      {/* Compatibility / Clearance Checks */}
      <section class="blueprint-section" aria-labelledby="bp-clearance-heading">
        <h2 id="bp-clearance-heading">Compatibility &amp; Clearance Checks</h2>
        {blueprint.clearanceChecks.length === 0 && (
          <p style="color:var(--text-tertiary); font-style:italic;">
            No clearance checks performed. Select a case and components to enable checks.
          </p>
        )}
        {blueprint.clearanceChecks.map((check, idx) => (
          <div key={idx} class={`blueprint-clearance-${check.result}`}>
            <div style="display:flex;align-items:center;gap:0.5rem;margin-bottom:0.25rem;">
              <span style="font-weight:700;font-size:0.875rem;">{check.label}</span>
              <span class={`badge ${check.result === 'pass' ? 'badge-safe' : check.result === 'fail' ? 'badge-danger' : 'badge-warning'}`}>
                {check.result === 'pass' ? 'PASS' : check.result === 'fail' ? 'FAIL' : 'UNKNOWN'}
              </span>
            </div>
            <p style="font-size:0.8125rem;margin:0;">
              {check.componentA} vs {check.componentB}<br />
              {check.detailA} &rarr; {check.detailB}
            </p>
            <p style="font-size:0.8125rem;margin-top:0.25rem;font-weight:600;">
              {check.message}
            </p>
          </div>
        ))}
      </section>

      {/* Power Analysis */}
      {blueprint.powerAnalysis && (
        <section class="blueprint-section" aria-labelledby="bp-power-heading">
          <h2 id="bp-power-heading">Power Supply Analysis</h2>
          <table class="blueprint-table">
            <tbody>
              <tr>
                <td style="font-weight:600;color:var(--text-primary);">Sustained Draw</td>
                <td style="font-variant-numeric:tabular-nums;">{blueprint.powerAnalysis.baseDraw}W</td>
              </tr>
              <tr>
                <td style="font-weight:600;color:var(--text-primary);">Transient Peak</td>
                <td style="font-variant-numeric:tabular-nums;">{blueprint.powerAnalysis.transientPeak}W</td>
              </tr>
              <tr>
                <td style="font-weight:600;color:var(--text-primary);">Recommended PSU</td>
                <td style="font-variant-numeric:tabular-nums;font-weight:700;color:var(--color-accent-cyan);">
                  &ge;{blueprint.powerAnalysis.recommendedWattage}W
                </td>
              </tr>
              <tr>
                <td style="font-weight:600;color:var(--text-primary);">Headroom</td>
                <td style="font-variant-numeric:tabular-nums;">
                  {blueprint.powerAnalysis.headroom}W ({blueprint.powerAnalysis.headroomPercent}%)
                </td>
              </tr>
              <tr>
                <td style="font-weight:600;color:var(--text-primary);">Verdict</td>
                <td>
                  <span class={`badge ${blueprint.powerAnalysis.verdict === 'yes' ? 'badge-safe' : blueprint.powerAnalysis.verdict === 'borderline' ? 'badge-warning' : 'badge-danger'}`}>
                    {blueprint.powerAnalysis.verdict === 'yes' ? 'SAFE' : blueprint.powerAnalysis.verdict === 'borderline' ? 'BORDERLINE' : 'INSUFFICIENT'}
                  </span>
                </td>
              </tr>
              {blueprint.powerAnalysis.perRail && (
                <>
                  <tr>
                    <td style="font-weight:600;color:var(--text-primary);">+12V Rail</td>
                    <td style="font-variant-numeric:tabular-nums;">
                      {blueprint.powerAnalysis.perRail.v12Amps}A / {blueprint.powerAnalysis.perRail.v12Watts}W
                    </td>
                  </tr>
                  <tr>
                    <td style="font-weight:600;color:var(--text-primary);">+5V Rail</td>
                    <td style="font-variant-numeric:tabular-nums;">
                      {blueprint.powerAnalysis.perRail.v5Amps}A / {blueprint.powerAnalysis.perRail.v5Watts}W
                    </td>
                  </tr>
                  <tr>
                    <td style="font-weight:600;color:var(--text-primary);">+3.3V Rail</td>
                    <td style="font-variant-numeric:tabular-nums;">
                      {blueprint.powerAnalysis.perRail.v3_3Amps}A / {blueprint.powerAnalysis.perRail.v3_3Watts}W
                    </td>
                  </tr>
                </>
              )}
            </tbody>
          </table>
        </section>
      )}

      {/* Build Order */}
      <section class="blueprint-section blueprint-build-order" aria-labelledby="bp-order-heading">
        <h2 id="bp-order-heading">Build Order</h2>
        <p style="font-size:0.8125rem;color:var(--text-tertiary);margin-bottom:1rem;">
          Recommended assembly sequence. Steps may vary based on component clearance and case layout.
        </p>
        <ol style="padding-left:1.25rem;margin:0;">
          {blueprint.buildOrder.map(step => (
            <li key={step.order}>
              <strong>{step.task}</strong><br />
              <span style="font-size:0.8125rem;color:var(--text-secondary);">{step.detail}</span>
            </li>
          ))}
        </ol>
      </section>

      {/* Thermal Paste */}
      {blueprint.thermalPasteAdvice && (
        <section class="blueprint-section" aria-labelledby="bp-paste-heading">
          <h2 id="bp-paste-heading">Thermal Paste Application</h2>
          <div style="display:flex;flex-direction:column;gap:0.5rem;">
            <p style="font-size:0.9375rem;font-weight:700;color:var(--text-primary);">
              Recommended method: {blueprint.thermalPasteAdvice.pattern}
            </p>
            <p style="font-size:0.8125rem;color:var(--text-secondary);">
              {blueprint.thermalPasteAdvice.rationale}
            </p>
            <p style="font-size:0.75rem;color:var(--text-tertiary);">
              Source: {blueprint.thermalPasteAdvice.source}
            </p>
          </div>
        </section>
      )}

      {/* Cable Plan */}
      {blueprint.cablePlan && (
        <section class="blueprint-section" aria-labelledby="bp-cable-heading">
          <h2 id="bp-cable-heading">Cable Plan</h2>
          <ul style="padding-left:1.25rem;margin:0;display:flex;flex-direction:column;gap:0.5rem;">
            {blueprint.cablePlan.cablesNeeded.map((cable, idx) => (
              <li key={idx} style="font-size:0.875rem;color:var(--text-secondary);">{cable}</li>
            ))}
          </ul>
          {!blueprint.cablePlan.daisyChainSafe && (
            <p style="font-size:0.8125rem;color:var(--status-danger);margin-top:0.75rem;padding:0.5rem;background:var(--status-danger-bg);border-radius:var(--radius-md);">
              ⚠ {blueprint.cablePlan.connectorType === '12v-2x6'
                ? 'Do not use daisy-chain PCIe adapters for 12V-2x6 GPUs. Use the native cable or a dedicated adapter.'
                : `This GPU requires ${blueprint.cablePlan.connectorCount} PCIe cables. Run separate cables from the PSU for each connector — do not use the daisy-chain pigtail on a single cable.`}
            </p>
          )}
        </section>
      )}

      {/* PSU Installation */}
      {blueprint.psuInstallationNote && (
        <section class="blueprint-section" aria-labelledby="bp-psu-install-heading">
          <h2 id="bp-psu-install-heading">PSU Installation</h2>
          <p style="font-size:0.875rem;color:var(--text-secondary);">
            <strong style="color:var(--text-primary);">Position:</strong> {blueprint.psuInstallationNote.position}<br />
            <strong style="color:var(--text-primary);">Fan direction:</strong> {blueprint.psuInstallationNote.fanDirection}<br />
            {blueprint.psuInstallationNote.note && (
              <><strong style="color:var(--text-primary);">Note:</strong> {blueprint.psuInstallationNote.note}</>
            )}
          </p>
        </section>
      )}

      {/* GPU Sag */}
      {blueprint.gpuSagAdvice && (
        <section class="blueprint-section" aria-labelledby="bp-sag-heading">
          <h2 id="bp-sag-heading">GPU Support Note</h2>
          <p style="font-size:0.875rem;color:var(--status-warning);padding:0.5rem;background:var(--status-warning-bg);border-radius:var(--radius-md);">
            {blueprint.gpuSagAdvice}
          </p>
        </section>
      )}

      {/* Tool Checklist */}
      <section class="blueprint-section" aria-labelledby="bp-tools-heading">
        <h2 id="bp-tools-heading">Tools Needed</h2>
        <ul style="padding-left:0;margin:0;list-style:none;display:flex;flex-direction:column;gap:0.5rem;">
          {blueprint.toolChecklist.map((tool, idx) => (
            <li key={idx} style="display:flex;align-items:center;gap:0.5rem;font-size:0.875rem;color:var(--text-secondary);">
              <span class={`blueprint-tool-dot ${tool.essential ? 'essential' : 'optional'}`} />
              <span>
                {tool.tool}
                {!tool.essential && <span style="font-size:0.75rem;color:var(--text-tertiary);"> (recommended)</span>}
              </span>
            </li>
          ))}
        </ul>
      </section>

      {/* Build Time */}
      <section class="blueprint-section" aria-labelledby="bp-time-heading">
        <h2 id="bp-time-heading">Estimated Build Time</h2>
        <p style="font-size:1.25rem;font-weight:800;color:var(--color-accent-cyan);">
          ~{blueprint.estimatedBuildTime.minutes} minutes
        </p>
        <p style="font-size:0.75rem;color:var(--text-tertiary);">
          {blueprint.estimatedBuildTime.note}
        </p>
      </section>

      {/* Print Footer */}
      <div class="blueprint-footer-print">
        Generated at PSUCheck.com/build-plan — {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
      </div>
    </div>
  );
}
